
all:
	manim -pql creating_mobjects.py CreatingMobjects 
	manim -pql shapes.py Shapes
	manim -pql placement.py MobjectPlacement
	manim -pql styling.py MobjectStyling
	manim -pql zorder.py MobjectZOrder
	manim -pql animation1.py SomeAnimations
	manim -pql animation2.py AnimateExample
	manim -pql runtime.py RunTime
	manim -pql counting.py CountingScene
	manim -pql transform.py ExampleTransform
	manim -pql rotation.py ExampleRotation
