= My Python Cookbook
:doctype: book
:publication-type: book
:toc: left
:toclevels: 3 
:source-highlighter: highlight.js 
:source-language: python
:icons: font

== Jupyter

[source,bash]
----
make              # Create .ipynb notebook if no .ipynb exists
jupyter-notebook  # Edit .ipynb and .py would be updated automatically
make              # Update .ipynb to .md to be included in asciidoc
make clean        # Remove generated .ipynb and .md
----

* You only need to include `.py` in version control.
** `.py` are for diff and `.ipynb` are for interactive editing.
** `.md` are the outputs to be included in asciidoc for quick reference since asciidoc cannot include `.ipynb` and we want to keep `.py` as raw files without output for version control

* In `Makefile`
. Use `jupytext` to generate `.ipynb` from `.py` and sync change from `.ipynb` back to `.py` for version control
. Use `jupyter nbconvert` to convert `ipynb` to `.md` for asciidoc inclusion.

https://jupytext.readthedocs.io/en/latest/using-cli.html[Use jupytext CLI]

https://jupytext.readthedocs.io/en/latest/faq.html[FAQ for jupytext]

=== Add a New Jupyter Notebook

For example, you created a `Sample.ipynb`, finished editing and saved the file.

Under the command line,

[source,bash]
-----
jupytext --set-formats ipynb,py:percent --sync Sample.ipynb
-----

. `Sample.py` would be generated by the above command and it would be synchronized by any editing of `Sample.ipynb`, you just need to edit `Sample.ipynb` and the change would be made to `Sample.py` automatically.

. Use `make` to create `Sample.md`.

. Make sure that `Sample.py` contains all updated content in `Sample.ipynb` and then `make clean` to remove both `Sample.ipynb` and `Sample.md` since we only need to keep `Sample.py` in version control.

== String

link:String.ipynb[String.ipynb]

include::String.md[]

== Built-in Functions

link:Enumerate.ipynb[Enumerate.ipynb]

include::Enumerate.md[]

link:Zip.ipynb[Zip.ipynb]

include::Zip.md[]

link:Sort.ipynb[Sort.ipynb]

include::Sort.md[]

== Functions

=== Default Arguments

link:DefaultArgument.ipynb[DefaultArgument.ipynb]

include::DefaultArgument.md[]

include::List.md[]