
all:
	manim -pql hello_world.py HelloWorld
	manim -pql markup.py SingleLineColor
	manim -pql fonts.py FontsExample
	manim -pql slant.py SlantsExample
	manim -pql weights.py DifferentWeight
	manim -pql color.py SimpleColor
	manim -pql t2c.py Textt2cExample
	manim -pql gradient.py GradientExample
	manim -pql t2g.py t2gExample
	manim -pql line_spacing.py LineSpacing
	manim -pql disable_ligature.py DisableLigature
	manim -pql iterate.py IterateColor
	manim -pql markup2.py MarkupTest
	manim -pql latex.py HelloLaTeX
	manim -pql mathtext.py MathTexDemo
	manim -pql ams.py AMSLaTeX
	manim -pql latex_color.py LaTeXAttributes
	manim -pql latex_usepackage.py AddPackageLatex
	manim -pql latex_substrings.py LaTeXSubstrings
	manim -pql latex_substrings_coloring_incorrect.py IncorrectLaTeXSubstringColoring
	manim -pql latex_substrings_coloring_correct.py CorrectLaTexSubstringColoring
	manim -pql index_labels.py IndexLabelsMathTex
	manim -pql french_cursive.py LaTeXMathFonts
	manim -pql ctex.py LaTeXTemplateLibrary
	manim -pql align.py LaTeXAlignEnvironment


clean:
	rm -rf __pycache__ media
