
all:
	manim -pql first.py CircleToSquare
	manim -pql position.py HelloCircle
	manim -pql animate1.py CircleAnnouncement
	manim -pql animate2.py AnimateSyntax
	manim -pql animate3.py DifferentRotations
	manim -pql cauchy_integral.py CauchyIntegralFormula
	manim -pql transform_equation.py TransformEquation
	manim -pql emphasis.py FormulaEmphasis
	manim -pql plot.py PlotExample

clean:
	rm -rf __pycache__ media

