

all:
	manim -pql circle.py CreateCircle
	manim -pql square_to_circle.py SquareToCircle
	manim -pql square_and_circle.py SquareAndCircle
	manim -pql animate.py AnimatedSquareToCorcle
	manim -pql animate.py DifferentRotations


clean:
	rm -rf __pycache__ media 

