

all:
	manim -pql circle.py CreateCircle
	manim -pql square_to_circle.py SquareToCircle
	manim -pql square_and_circle.py SquareAndCircle
	manim -pql animate.py AnimatedSquareToCorcle
	manim -pql animate.py DifferentRotations
	manim -pqh square_to_circle.py SquareToCircle
	manim -sqh square_to_circle.py SquareToCircle

clean:
	rm -rf __pycache__ media 

